# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ndejsong <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/01 05:30:46 by ndejsong          #+#    #+#              #
#    Updated: 2022/07/01 05:41:33 by ndejsong         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRC_FILE =

OBJ_FILE = $(SRC_FILE:.c=.o)

CC = gcc
CC_FLAG = -Wall -Wextra -Werror

$(NAME):
	@$(CC) $(CC_FLAG) -c $(SRC_FILE)
